package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// WriteConfig writes setup results to ~/.lrc.toml.
func WriteConfig(result *SetupResult) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to determine home directory: %w", err)
	}

	configPath := filepath.Join(homeDir, ".lrc.toml")

	content := fmt.Sprintf(`# LiveReview CLI configuration
# Generated by: lrc setup
# Date: %s

api_key = %q
api_url = %q
user_email = %q
user_first_name = %q
user_last_name = %q
avatar_url = %q
user_id = %q
org_id = %q
org_name = %q
jwt = %q
refresh_token = %q
`,
		time.Now().Format(time.RFC3339),
		result.PlainAPIKey,
		CloudAPIURL,
		result.Email,
		result.FirstName,
		result.LastName,
		result.AvatarURL,
		result.UserID,
		result.OrgID,
		result.OrgName,
		result.AccessToken,
		result.RefreshToken,
	)

	if err := WriteFileAtomically(configPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// WriteFileAtomically atomically replaces a target file with provided content.
func WriteFileAtomically(path string, data []byte, mode os.FileMode) error {
	tmpFile, err := os.CreateTemp(filepath.Dir(path), ".lrc-config-*.tmp")
	if err != nil {
		return fmt.Errorf("failed to create temporary file: %w", err)
	}
	tmpPath := tmpFile.Name()

	if _, err := tmpFile.Write(data); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write temporary file: %w", err)
	}

	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to finalize temporary file: %w", err)
	}

	if err := os.Chmod(tmpPath, mode); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to set permissions on temporary file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to atomically replace %s: %w", path, err)
	}

	return nil
}
